---
- name: Install Cassandra
  apt: name=cassandra={{datastax.cass_version}} update-cache=yes force=yes state=present
  register: cassandra_install
  tags:
    - packages

- name: Install OpsCenter
  apt: name=opscenter update-cache=yes force=yes state=present
  register: cassandra_install
  tags:
    - packages
