- name: Delete DataStax DB Nodes
  gather_facts: False
  hosts: localhost
  tasks:
    - name: Delete DataStax DB Nodes
      local_action:
        module: rax
        credentials: ~/.rackspace_cloud_credentials
        name: cass-node-{{ item.value.region }}-%02d
        exact_count: yes
        flavor: performance1-2
        image: 6f29d6a6-9972-4ae0-aa80-040fa2d6a9cf
        region: "{{ item.value.region }}"
        wait: yes
        state: absent
        group: ds_db
        count: "{{ item.value.node_count }}"
        files:
           /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        networks:
           - private
           - public
      with_dict: cluster_opts
      register: rax
