---
- name: stop cassandra from running with default config
  template: src=policy-rc.d.j2 dest=/usr/sbin/policy-rc.d mode=0755
  tags:
     - configuration

- name: Install Cassandra
  apt: pkg=cassandra update-cache=yes force=yes state=present
  register: cassandra_install
  tags:
    - packages

- name: Register ip for config file
  shell: ifconfig eth1 | awk '/inet addr/' | cut -d':' -f2 | awk '{print $1}'
  register: clus_ip

- name: Install Cassandra config file
  template: src=cassandra-{{cassandra.version_branch}}.j2 dest=/etc/cassandra/cassandra.yaml
  tags:
    - configuration

- name: Install Cassandra Java Config File
  template: src=cassandra-{{cassandra.version_branch}}-env.j2 dest=/etc/cassandra/cassandra-env.yaml
  tags:
    - configuration

- name: Install log4j config file
  template: src=log4j-server.properties dest=/etc/cassandra/log4j-server.properties
  tags:
    - configuration

- name: remove policy-rc.d file
  file: path=/usr/sbin/policy-rc.d state=absent

- name: restart cassandra
  service: name=cassandra state=restarted
